# Each new term in the Fibonacci sequence is generated by adding the previous 
# two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed 
# four million, find the sum of the even-valued terms.

# Create empty list for Fibonacci Sequence:
fibonacci = []

# Create Fibonacci Sequence up to four million:
i = j = n = 1
while n < 4000000:
	print n
	fibonacci.append(n)
	n = i + j
	i = j
	j = n
print fibonacci

# Select even (n % 2 == 0) values and print them to fib_even list:
fib_even = []
for n in fibonacci:
	if n % 2 == 0:
		fib_even.append(n)
print fib_even

# Sum up even values and assign to sum:
sum = 0
for n in fib_even:
	sum +=n
print sum

	
	